version: '3.9'

services:
  vscode_api:
    build: 
      context: ./
      dockerfile: Dockerfile
    command: /bin/bash -c "while sleep 1000; do :; done"
    working_dir: /home/prod
    networks:
      - api-network
    volumes:
      - ./:/home/prod:cached
    environment:
      - DB_HOST=dbms
      - DB_USER=api-dev
      - DB_DATABASE=projet_production
      - DB_PASSWORD=api-dev-password
    
  dbms:
    image: mariadb
    restart: always
    ports:
      - "3309:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=rootpassword
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - ./dbms/dbms-data:/var/lib/mysql
      - ./dbms/mariadb.cnf:/etc/mysql/mariadb.cnf
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
    name: api-network
